server:
  port: 2004



spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: lhy_tx_group
    nacos:
      discovery:
        server-addr: 192.168.194.137:1111
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: Sxd12345


feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath*:mapper/*.xml


